### ISSUE TITLE
How to set up customized ip address?

### ISSUE THREAD

**Issue by iiiir** [klarman-cell-observatory/cirrocumulus#10]
I am using the docker version on my macbook at it worked:
$ docker run -it -p 5000:5000 --rm -v `pwd`:/data cumulusprod/cirrocumulus cirro launch /data/pbmc3k.h5ad --host 0.0.0.0

Change IP to 127.0.0.1 will run but cannot open the link. Says "This page isn’t working":
$ docker run -it -p 5000:5000 --rm -v `pwd`:/data cumulusprod/cirrocumulus cirro launch /data/pbmc3k.h5ad --host 127.0.0.1

And changing the ip address to my macbook's ip address with not run:
$ docker run -it -p 5000:5000 --rm -v `pwd`:/data cumulusprod/cirrocumulus cirro launch /data/pbmc3k.h5ad --host [ip adress of my macbook]

...
OSError: [Errno 99] Cannot assign requested address

Question:
How can i set up with my ip address, or hostname?
Thanks,

**Comment by iiiir** [comment]
Another question: 
I was able to run the app with miniconda, but it cannot find files.

$ cirro launch ./data/pbmc3k.h5ad --host [host ip addr] --port 8080
![image](https://user-images.githubusercontent.com/4137873/89115733-75f1d580-d440-11ea-94e8-e5a513953758.png)

[01/Aug/2020 21:46:08] "GET /api/filters?id=pbmc3k.h5ad HTTP/1.1" 200 -
[2020-08-01 21:46:08,763] ERROR in app: Exception on /api/schema [GET]
Traceback (most recent call last):
  File "/apps/python/Miniconda/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/apps/python/Miniconda/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/apps/python/Miniconda/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/python/Miniconda/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/cirrocumulus/api.py", line 127, in handle_schema
    return to_json(get_schema_and_dataset()[0])
  File "/apps/python/Miniconda/lib/python3.7/site-packages/cirrocumulus/api.py", line 119, in get_schema_and_dataset
    schema = dataset_api.schema(dataset)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/cirrocumulus/dataset_api.py", line 46, in schema
    value = provider.schema(self.fs_adapter.get_fs(path), path)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/cirrocumulus/anndata_dataset.py", line 57, in schema
    return SimpleData.schema(self.get_data(path))
  File "/apps/python/Miniconda/lib/python3.7/site-packages/cirrocumulus/anndata_dataset.py", line 50, in get_data
    adata = self.read_adata(path)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/cirrocumulus/anndata_dataset.py", line 33, in read_adata
    return anndata.read(path, backed=self.backed)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 447, in read_h5ad
    constructor_args = _read_args_from_h5ad(filename=filename, chunk_size=chunk_size)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 486, in _read_args_from_h5ad
    _read_key_value_from_h5(f, d, key, chunk_size=chunk_size)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 510, in _read_key_value_from_h5
    _read_key_value_from_h5(f, d[key_write], key + '/' + k, k, chunk_size)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 510, in _read_key_value_from_h5
    _read_key_value_from_h5(f, d[key_write], key + '/' + k, k, chunk_size)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 544, in _read_key_value_from_h5
    key, value = postprocess_reading(key, value)
  File "/apps/python/Miniconda/lib/python3.7/site-packages/anndata/readwrite/read.py", line 541, in postprocess_reading
    value = value.astype(new_dtype)
ValueError: invalid shape in fixed-type tuple.
[ip adress] - - [01/Aug/2020 21:46:08] "GET /api/schema?id=pbmc3k.h5ad HTTP/1.1" 500 -

**Comment by bli25broad** [comment]
@iiiir Thanks a lot for your interest in Cirrocumulus. @joshua-gould will look into your issue tomorrow.

Best,
Bo

**Comment by joshua-gould** [comment]
Can you please confirm that the path to your h5ad file is correct?

**Comment by iiiir** [comment]
@joshua-gould , If you are referring to my second post yes i can conform the path is correct. I was running under the same folder -- also tried full path which gave same error. **HOWEVER**, the run was in a conda environment, which I am not sure if the path should be specified otherwise. 

The reason i use conda is because some dependent libraries cannot be installed as I am not admin for the cluster. e.g. cython and pandas (I do not have permission to uninstall older versions of cython).

I was able to run the command successfully with regular python environment (without conda), on my personal macbook.

**Comment by joshua-gould** [comment]
Sorry for the delay in my response. Were you able to resolve these issues?
