### ISSUE TITLE
Error while running example

### ISSUE THREAD

**Issue by parashardhapola** [klarman-cell-observatory/cirrocumulus#11]
Hi,

I tried running this:  `cirro launch pbmc3k.h5ad --markers markers.json` using the example data.

Got this error:
```
/home/parashar/miniconda3/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "/home/parashar/miniconda3/bin/cirro", line 10, in <module>
    sys.exit(main())
  File "/home/parashar/miniconda3/lib/python3.7/site-packages/cirrocumulus/__main__.py", line 20, in main
    cmd.main(command_args)
  File "/home/parashar/miniconda3/lib/python3.7/site-packages/cirrocumulus/launch.py", line 143, in main
    configure(args.dataset, args.spatial, args.backed, args.markers)
  File "/home/parashar/miniconda3/lib/python3.7/site-packages/cirrocumulus/launch.py", line 102, in configure
    key = os.path.splitext(os.path.basename(marker_json))[0]
  File "/home/parashar/miniconda3/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not dict
```

cirrocumulus version: 1.1.7

Parashar

**Comment by joshua-gould** [comment]
Thanks for reporting. This is fixed in 1.1.7.post1.
